# Site settings
title: *folio
email: you@example.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl: /portfolio/ # the subpath of your site, e.g. /blog/
url: https://www.webdevholland.com/portfolio/ # the base hostname & protocol for your site
twitter_username: webdevholland
github_username:  webdevholland

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/portfolio/page:num/"


collections:
  projects:
    output: true
    permalink: projects/:path/
 # web-development:
 #   output: true
 #   permalink: /web-development/:path/
 # design:
 #   output: true
 #   permalink: /design/:path/


